services:
  web-catchly:
    build: ./src
    container_name: web-catchly
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=blog_db
      - MYSQL_USER=blog_user
      - MYSQL_PASSWORD=blog_pass
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: blog_db_container
    environment:
      MYSQL_ROOT_PASSWORD: blog_root_pass
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped

volumes:
  db_data:

