services:
  web-catchly:
    build: ./src
    container_name: web-catchly
    ports:
      - "8010:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=blog_db
      - MYSQL_USER=blog_user
      - MYSQL_PASSWORD=blog_pass
      - N8N_WEBHOOK_POST_CREATED=http://n8n:5678/webhook/post-created
      - N8N_WEBHOOK_COMMENT_CREATED=http://n8n:5678/webhook/comment-created
      - N8N_SHARED_TOKEN=super_secure_shared_token_123
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: blog_db_container
    environment:
      MYSQL_ROOT_PASSWORD: blog_root_pass
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: unless-stopped


  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  db_data:
  n8n_data:

